name: Run Cucumber Tests and Upload Reports to Drive

on:
  workflow_dispatch:
    inputs:
      cucumber_tag:
        description: 'Select Cucumber Tag to Run'
        required: true
        type: choice
        options:
          - '@SU_TC01_Register_with_valid_credentials'
          - '@SU_TC02_Register_with_leaving_one_mandatory_field_blank'
          - '@SU_TC03_Register_with_existing_accounts_credentials'
          - '@SU_TC04_Navigate_to_Registration_Page_from_Login_Page'
          - '@SU_TC05_login_valid_credentials'
          - '@SU_TC06_Login_with_Valid_Username_Invalid_Password'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Maven Test with Selected Tag
        run: |
          echo "Running tests with tag: ${{ github.event.inputs.cucumber_tag }}"
          mvn clean test -Dcucumber.filter.tags="${{ github.event.inputs.cucumber_tag }}"

      - name: Debug Test Output Locations
        run: |
          echo "=== Searching for Report Directories ==="
          find . -type d | grep -i "report\|extent\|output\|result" || echo "No report directories found"
          echo "=== Maven Target Contents ==="
          ls -R target || echo "No target directory found"

      - name: Setup Google Drive Uploader
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          wget https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive_2.1.1_linux_386.tar.gz
          tar -xzf gdrive_2.1.1_linux_386.tar.gz
          chmod +x gdrive
          ./gdrive version

      - name: Find and Upload Extent Reports
        env:
          GDRIVE_SERVICE_ACCOUNT_JSON: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
          # Try common report locations (add more if needed)
          REPORT_PATHS=(
            "target/extent-reports"
            "target/ExtentReports"
            "ExtentReports"
            "test-output/ExtentReports"
            "AmericanHealth/ExtentReports"
            "target/surefire-reports"
            "build/reports/tests"
          )

          FOUND_REPORTS=false
          for path in "${REPORT_PATHS[@]}"; do
            if [ -d "$path" ]; then
              echo "::group::Found reports at: $path"
              echo "=== Report Contents ==="
              ls -R "$path"
              echo "::endgroup::"
              
              echo "$GDRIVE_SERVICE_ACCOUNT_JSON" > sa.json
              chmod 600 sa.json
              
              echo "=== Uploading Reports ==="
              if ./gdrive upload \
                --service-account "$(pwd)/sa.json" \
                --recursive \
                --parent "$GDRIVE_FOLDER_ID" \
                "$path"; then
                echo "::notice::Successfully uploaded reports from $path"
                FOUND_REPORTS=true
                break
              else
                echo "::warning::Failed to upload reports from $path"
              fi
            fi
          done

          if [ "$FOUND_REPORTS" = false ]; then
            echo "::error::No ExtentReports directory found in any expected location!"
            echo "Searched in: ${REPORT_PATHS[*]}"
            echo "=== Full Directory Structure ==="
            find . -type d
            exit 1
          fi

      - name: Cleanup
        run: |
          rm -f gdrive* sa.json
