name: Run Selenium Test & Upload Extent Report

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Python Dependencies
        run: |
          pip install google-api-python-client google-auth google-auth-oauthlib

      - name: Run Maven Test to Generate Extent Report
        run: mvn clean test -Dcucumber.filter.tags=@C_TC_01_Corporate_Registration_with_Valid_Details

      - name: Upload Latest SparkReport to Google Drive
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
          python <<EOF
          import os, json, zipfile
          from google.oauth2 import service_account
          from googleapiclient.discovery import build
          from googleapiclient.http import MediaFileUpload

          def get_latest_spark_folder():
              base = "ExtentReports"
              folders = [f for f in os.listdir(base) if f.startswith("SparkReport_") and os.path.isdir(os.path.join(base, f))]
              folders.sort(reverse=True)
              return os.path.join(base, folders[0]) if folders else None

          def zip_folder(folder_path, output_path):
              with zipfile.ZipFile(output_path, 'w') as zipf:
                  for root, _, files in os.walk(folder_path):
                      for file in files:
                          path = os.path.join(root, file)
                          zipf.write(path, os.path.relpath(path, start=folder_path))

          def upload_to_drive(zip_path, zip_name, folder_id):
              creds_dict = json.loads(os.environ['GDRIVE_CREDENTIALS'])
              creds = service_account.Credentials.from_service_account_info(creds_dict, scopes=["https://www.googleapis.com/auth/drive"])
              service = build("drive", "v3", credentials=creds)
              file_metadata = { 'name': zip_name, 'parents': [folder_id] }
              media = MediaFileUpload(zip_path, mimetype='application/zip')
              file = service.files().create(body=file_metadata, media_body=media, fields='id').execute()
              print("Uploaded file ID:", file.get("id"))

          latest_folder = get_latest_spark_folder()
          if not latest_folder:
              print("No SparkReport folder found.")
              exit(1)
          zip_name = latest_folder + ".zip"
          zip_folder(latest_folder, zip_name)
          upload_to_drive(zip_name, os.path.basename(zip_name), os.environ['GDRIVE_FOLDER_ID'])
